name: Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # 允许手动触发
  workflow_dispatch:
  # 当文档仓库更新时触发
  repository_dispatch:
    types: [docs-updated]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout website repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean and clone docs content
        run: |
          # 删除可能存在的 content 目录或符号链接
          rm -rf content
          # 克隆文档仓库
          git clone https://github.com/JiajiaHuang/sbim_docs.git content
          echo "Content cloned successfully"

      - name: Verify content structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Content directory:"
          ls -la content/ || echo "Content directory not found"
          echo "Content docs directory:"
          ls -la content/docs/ || echo "Content docs directory not found"

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # 可选：自定义域名
          # cname: docs.sb.im
